parameters:
  containerServiceEndpoint: 'iUSDevContainer'
  storageSubscription: ''
  storageContainerName: ''
  storageRMStorageAccount : ''
  registry: 'iusdev.azurecr.io'
  baseContainerUrl: https://iusux.blob.core.windows.net/iusux

jobs:
  - job: DockerBuilds
    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      version: 0.0.0.0
      semVersion: 0.0.0
    steps:
      - task: Docker@1
        displayName: Container registry login
        inputs:
          azureSubscriptionEndpoint: ${{ parameters.containerServiceEndpoint }}
          azureContainerRegistry: ${{ parameters.registry }}
          command: login
      - task: Docker@1
        displayName: Build image
        inputs:
          command: build
          azureSubscriptionEndpoint: ${{ parameters.containerServiceEndpoint }}
          azureContainerRegistry: ${{ parameters.registry }}
          dockerFile: Dockerfile
          arguments: --build-arg baseContainerUrl ${{ parameters.baseContainerUrl }} --build-arg cdnSourceFolder=$(ArtifactStagingDirectory )
          addDefaultLabels: false
      - task: AzureFileCopy@3
        inputs:
          sourcePath: $(ArtifactStagingDirectory )
          azureSubscription: '${{ parameters.storageSubscription }}'
          destination: azureBlob
          storage:  ${{ parameters.storageRMStorageAccount }}
          containerName: ${{ parameters.storageContainerName }}
          additionalArgumentsForBlobCopy: "/SetContentType"
