parameters:
  Name : 'DotNet_WebBuild'
  Project : ''
  webProject : ''
  nugetConfigPath : 'application/NuGet.Config'
  majorVersion: 0
  stateCode: 0

jobs:
  - job: ${{ parameters.Name }}
    variables:
      version: ${{ parameters.stateCode }}.${{ parameters.majorVersion }}.$([math]::floor($(build.buildId)/10000)).$($(build.buildId)%10000)
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: |
          echo "Setting csproj Version To $version"
          find src/ -type f -iname '*.csproj' -exec  sed -i "s/0\.0\.0\-INTERNAL/$version/g" "{}" \;
          grep "<VersionPrefix>.*</VersionPrefix>" -R .
        displayName: Set Project Version
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: 'application/**/*.csproj'
          feedsToUse: config
          nugetConfigPath: ${{ parameters.nugetConfigPath }}
      - script: dotnet build ${{ parameters.Project }}${{ parameters.webProject }} --configuration Release
        displayName: Build
      - task: DotNetCoreCLI@2
        displayName: Run Tests
        inputs:
          command: test
          projects: '**/*Tests/*.csproj'
          arguments: '--configuration Release'
      - script: dotnet publish ${{ parameters.Project }}${{ parameters.webProject }} --configuration Release --output  -o $(Build.ArtifactStagingDirectory)/Web
        displayName: Publish
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: $(Build.ArtifactStagingDirectory)/Web
          archiveFile: $(Build.ArtifactStagingDirectory)/Web.zip
          quiet: false
          includeRootFolder: false
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish : '$(Build.ArtifactStagingDirectory)/Web.zip'
          artifactName: artifacts
