parameters:
  serviceProject : ''
  nugetConfigPath : 'application/NuGet.Config'

jobs:
  - job: DotNet_ServiceBuild
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - task: DotNetCoreCLI@2
        displayName: Restore
        inputs:
          command: restore
          projects: 'application/**/*.csproj'
          feedsToUse: config
          nugetConfigPath: ${{ parameters.nugetConfigPath }}
      - script: dotnet build ${{ parameters.serviceProject }} --configuration release -o $(Build.ArtifactStagingDirectory)/service 
        displayName: Build
      - task: DotNetCoreCLI@2
        displayName: Run Tests
        inputs:
          command: test
          projects: '**/*Tests/*.csproj'
          arguments: '--configuration release'


  