parameters:
  Name : 'EFMigration'
  Project: '' # The full path to the csproj (including the *.cspoj name)
  DBContext: '' # The name of the file that implements the DbContext without the namespace

jobs:
  - job: ${{ parameters.Name }}
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - script: dotnet --version
        displayName: Print version
      - script: dotnet ef migrations script --help
        displayName: Print Help
      - script: dotnet ef database update --project ${{ parameters.Project }}
        displayName: Updating the Local Database
      - script: dotnet ef migrations script --output $(Build.ArtifactStagingDirectory)/$(build.buildId).sql --idempotent --project ${{ parameters.Project }} --context ${{ parameters.DBContext }}
        displayName: Generate EF Migration Script
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish : '$(Build.ArtifactStagingDirectory)'
          artifactName: artifacts
