parameters:
  Name : 'EFMigration'
  Project: '' # The full path to the csproj (including the *.cspoj name)
  ProjectDirectory : ''
  DBContext: '' # The name of the file that implements the DbContext without the namespace

jobs:
  - job: ${{ parameters.Name }}
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: dotnet build
        workingDirectory: ${{ parameters.ProjectDirectory }}
        displayName: "Building Project"
      - script: dotnet ef migrations script --output $(Build.ArtifactStagingDirectory)/$(build.buildId).sql --idempotent --context ${{ parameters.DBContext }} --verbose --no-build
        displayName: Generate EF Migration Script
        workingDirectory: ${{ parameters.ProjectDirectory }}
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish : '$(Build.ArtifactStagingDirectory)'
          artifactName: artifacts
