parameters:
  Name : 'EFMigration'
  Project: ''
  nugetConfigPath : 'application/NuGet.Config'

jobs:
  - job: ${{ parameters.Name }}
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: dotnet ef migrations script --output $(Build.ArtifactStagingDirectory) --idempotent
        displayName: Generate EF Migration Script
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish : '$(Build.ArtifactStagingDirectory)'
          artifactName: artifacts
