parameters:
  Name : 'NugetPackage'
  Project: '' # The full path to the csproj (including the *.cspoj name)
  FeedName: '' # The Feed name to publish to

jobs:
  - job: ${{ parameters.Name }}
    pool:
      vmImage: 'Ubuntu-16.04'
    steps:
      - script: dotnet build ${{ parameters.Project }}
        displayName: "Building Project"
      - script : dotnet pack ${{ parameters.Project}}
        displayName: Nuget Pack
      - task: NuGetCommand@2
        displayName: 'NuGet push'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          command: push
          publishVstsFeed: '${{ parameters.FeedName}}'
          allowPackageConflicts: false
