parameters:
  Name : 'NugetPackage'
  Project: '' # The full path to the csproj (including the *.cspoj name)
  FeedName: '' # The Feed name to publish to
  majorVersion: 0
  stateCode: 0

jobs:
  - job: ${{ parameters.Name }}
    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      version: 0.0.0
      semVersion: 0.0.0
    steps:
      - powershell: |
          Write-Host "##vso[task.setvariable variable=version]${{ parameters.stateCode }}.${{ parameters.majorVersion }}.$([math]::floor($(build.buildId)/10000)).$($(build.buildId)%10000)"
          Write-Host "##vso[task.setvariable variable=semVersion]${{ parameters.majorVersion }}.$([math]::floor($(build.buildId)/10000)).$($(build.buildId)%10000)"
          Write-Host "Version = $(version)"
        displayName: Set Version Variable
      - script: |
          echo "Setting csproj Version To $version"
          find src/ -type f -iname '*.csproj' -exec  sed -i "s/0\.0\.0\-INTERNAL/$version/g" "{}" \;
          grep "<VersionPrefix>.*</VersionPrefix>" -R .
        displayName: Set Project Version
      - script: dotnet build ${{ parameters.Project }}
        displayName: Building Project
      - script : dotnet pack ${{ parameters.Project}} -c Release --include-symbols --include-source -o $(Build.ArtifactStagingDirectory)/dist
        displayName: Nuget Pack
      - task: NuGetCommand@2
        displayName: 'NuGet push'
        condition:
          and
          (
            succeeded(),
            or
            (
              eq(variables['Build.SourceBranch'], 'refs/heads/master'),
              and
              (
                eq(variables['UsingDevelopBranch'], 'true'),
                eq(variables['Build.SourceBranch'], 'refs/heads/devlop')
              )
            )
          )
        inputs:
          command: push
          publishVstsFeed: '${{ parameters.FeedName}}'
          allowPackageConflicts: false
