parameters:
  containerServiceEndpoint: 'iUSDevContainer'
  registry: 'iusdev.azurecr.io'
  project: ''
  helmChartLocation: 'application/helm'
  helmChartName: ''
  majorVersion: 0
  stateCode: 0

jobs:
  - job: DockerBuilds
    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      version: 0.0.0.0
      semVersion: 0.0.0
    steps:
      - script: |
          ##vso[task.setvariable variable=version]${{ parameters.stateCode }}.${{ parameters.majorVersion }}.$([math]::floor($(build.buildId)/10000)).$($(build.buildId)%10000)
          ##vso[task.setvariable variable=semVersion]${{ parameters.majorVersion }}.$([math]::floor($(build.buildId)/10000)).$($(build.buildId)%10000)
          echo "Setting csproj Version To $version"
          find application/ -type f -iname '*.csproj' -exec  sed -i "s/0\.0\.0\-INTERNAL/$version/g" "{}" \;
          grep "<VersionPrefix>.*</VersionPrefix>" -R .
        displayName: Set Project Version
      - template: docker-pipeline.yaml
        parameters:
          version: '$(version)'
          semVersion: '$(semVersion)'
          containerServiceEndpoint: '${{ parameters.containerServiceEndpoint }}'
          registry: '${{ parameters.registry }}'
          project: '${{ parameters.project }}'
          helmChartLocation: '${{ parameters.helmChartLocation }}'
          helmChartName : '${{ parameters.helmChartName }}'
          latestName: '$(registry)/$(project):latest'
          imageName: '$(registry)/$(project):$(version)'
