parameters:
  containerServiceEndpoint: 'iUSDevContainer'
  registry: 'iusdev.azurecr.io'
  project: ''
  helmChartLocation: 'application/helm'
  helmChartName: ''
  majorVersion: 0
  stateCode: 0

jobs:
  - job: DockerBuilds
    pool:
      vmImage: 'Ubuntu-16.04'
    variables:
      version: 0.0.0
      semVersion: 0.0.0
    steps:
      - template: steps/set-version-variable.yaml
      - template: docker-pipeline.yaml
        parameters:
          version: '$(version)'
          semVersion: '$(semVersion)'
          containerServiceEndpoint: '${{ parameters.containerServiceEndpoint }}'
          registry: '${{ parameters.registry }}'
          project: '${{ parameters.project }}'
          helmChartLocation: '${{ parameters.helmChartLocation }}'
          helmChartName : '${{ parameters.helmChartName }}'
          latestName: '$(registry)/$(project):latest'
          imageName: '$(registry)/$(project):$(version)'

