parameters:
  stateCode: 0
  majorVersion: 0

steps:
- powershell: |
    Write-Host "Attempting to set variable to ${{ parameters.stateCode }}.${{ parameters.majorVersion }}.$([math]::floor($(build.buildId)/10000)).$($(build.buildId)%10000)"
    $tmpSemversion = "${{ parameters.majorVersion }}.$([math]::floor($(build.buildId)/10000)).$($(build.buildId)%10000)"
    $tmpVersion = "${{ parameters.stateCode }}.$tmpSemversion"

    Write-Host "Set intermeidate variables $tmpSemversion and $tmpVersion"

    Write-Host "##vso[task.setvariable variable=version;]$tmpVersion"
    Write-Host "##vso[task.setvariable variable=semVersion;]$tmpSemversion"
    Write-Host "Setting csproj Version To $version"
    Write-Host "Setting semVersion to $semVersion"
  displayName: Calculating Version