parameters:
  containerServiceEndpoint: 'VDOL-UI-DEV'
  helmChartLocation: ''
  helmChartName : ''
  Name: ''
  majorVersion: 0
  stateCode: 0
  registry: 'vtiusdev.azurecr.io'
  dockerBuildToolsACR: 'vtiusdev'

jobs:
  - job: ${{ parameters.Name }}
    pool:
      vmImage: 'Ubuntu-18.04'
    variables:
      version: 0.0.0.0
      semVersion: 0.0.0 
    steps:
      - powershell: |
          Write-Host "Attempting to set variable to ${{ parameters.stateCode }}.${{ parameters.majorVersion }}.$([math]::floor($(build.buildId)/10000)).$($(build.buildId)%10000)"
          $tmpSemversion = "${{ parameters.majorVersion }}.$([math]::floor($(build.buildId)/10000)).$($(build.buildId)%10000)"
          $tmpVersion = "${{ parameters.stateCode }}.$tmpSemversion"

          Write-Host "Set intermeidate variables $tmpSemversion and $tmpVersion"

          Write-Host "##vso[task.setvariable variable=version;]$tmpVersion"
          Write-Host "##vso[task.setvariable variable=semVersion;]$tmpSemversion"
          Write-Host "Setting csproj Version To $(version)"
          Write-Host "Setting semVersion to $(semVersion)"
        displayName: Calculating Version
      - task: Docker@1
        displayName: Container registry login
        inputs:
          azureSubscriptionEndpoint : ${{ parameters.containerServiceEndpoint }}
          azureContainerRegistry : ${{ parameters.registry }}
          command: login
      - template: helm-chart-pipeline-template.yaml
        parameters:
          version: '$(version)'
          semVersion: '$(semVersion)'
          containerServiceEndpoint: '${{ parameters.containerServiceEndpoint }}'
          helmChartLocation: '${{ parameters.helmChartLocation }}'
          helmChartName : '${{ parameters.helmChartName }}'
          dockerBuildToolsACR: ''${{ parameters.dockerBuildToolsACR }}'

