# Default values for employermanagement-web.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: iusdev.azurecr.io/{{imageName}}
  tag: 0.0.0-INTERNAL

clientStateName : Consortium

nameOverride: ""
fullnameOverride: ""

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
